site_name: Predição de Churn
site_author: Gomes, E, Melo, L & Kao, L.
site_url: https://esdrasgc.github.io/customer-churn-prediction-kaggle
repo_url: https://github.com/esdrasgc/customer-churn-prediction-kaggle
repo_name: github/customer-churn-prediction-kaggle

theme:
  name: material
  palette:
    # primary: grey
    # Light mode
    - scheme: default
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.expand
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - markdown_grid_tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 2-5

plugins:
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - git-committers:
      repository: esdrasgc/customer-churn-prediction-kaggle
      branch: main
  - search
  - badges
  - minify:
      minify_html: true
  - markdown-exec
  - render_swagger:
      allow_arbitrary_locations : true
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"
  - mkdocs-jupyter:
      execute: true
      include_source: true
      kernel_name: python3
extra_javascript:
  - javascripts/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  
extra_css:
  - stylesheets/overrides.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css

nav:
  - Home: index.md
  - Etapas do projeto:
    - Dataset Selection: ./dataset/dataset_selection.md
    - Dataset Explanation: ./dataset/dataset_explanation.md
    - Data Cleaning & Normalization: ./training/data_cleaning_normalization.md
    - MLP Implementation: ./training/mlp_implementation.md
    - Model Training: ./training/model_training.md
    - Training & Testing Strategy: ./training/training_testing_strategy.md
    - Error Curves & Visualization: ./evaluation/error_curves.md
    - Evaluation Metrics: ./evaluation/metrics.md
  - Competition Submission: ./competition.md
  - Conclusion: ./conclusion.md
  - References: ./references.md